/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.*;
import ventanas.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ventanas.Inicio;

/**
 *
 * @author Maria Guadalupe López and Kenneth López
 */
public class Login extends javax.swing.JFrame {

    public static String user = "";
    String pass = "";
    int contador = 3;

    public Login() {
        initComponents();
        setSize(400, 500);
        setResizable(false);
        setTitle("Acceso al Sistema");
        setLocationRelativeTo(null);

        ImageIcon fondo = new ImageIcon("src/images/Sist_Coop.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(),
                jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_fondo.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_user = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_Acceder = new javax.swing.JButton();
        jLabel_Intentos = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_user.setBackground(new java.awt.Color(51, 102, 255));
        txt_user.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, -1));

        txt_password.setBackground(new java.awt.Color(51, 102, 255));
        txt_password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 210, -1));

        btn_Acceder.setBackground(new java.awt.Color(51, 102, 255));
        btn_Acceder.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn_Acceder.setForeground(new java.awt.Color(255, 255, 255));
        btn_Acceder.setText("Acceder");
        btn_Acceder.setBorder(null);
        btn_Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccederActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 210, 35));

        jLabel_Intentos.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel_Intentos.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel_Intentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 210, 10));

        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox1.setText("Mostrar Contraseña");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            txt_password.setEchoChar((char) 0);
        } else {
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccederActionPerformed
        int resultado = 0;
        user = txt_user.getText().trim();
        pass = String.valueOf(txt_password.getPassword());

        if (contador > 1) {
            if (!user.equals("") && !pass.equals("")) {
                try {
                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement(
                            "select * from usuarios where username = '" + user
                            + "' and password = '" + pass + "'");

                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {
                        String estatus = rs.getString("estatus");
                        resultado = 1;

                        if (resultado == 1) {
                            Inicio form = new Inicio();
                            form.setVisible(true);
                            this.dispose();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos");
                        txt_password.setText("");
                        txt_user.setText("");
                        contador = (contador - 1);
                        jLabel_Intentos.setText("Intentos restantes: " + contador);
                    }
                } catch (SQLException e) {
                    System.err.println("Error en el boton acceder." + e);
                    JOptionPane.showMessageDialog(null, "¡Error al iniciar sesion!, Contacte al administrador");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Demasiados intentos, ¡El programa se cerrara!");
            this.dispose();
        }
    }//GEN-LAST:event_btn_AccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Acceder;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel_Intentos;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
